<?php

$plugin = array(
  'title' => t('Four mini twocol'),
  'category' => t('Adapt'),
  'icon' => 'adapttwocolmini.png',
  'theme' => 'adapttwocolmini',
  'css' => 'adapttwocolmini.css',
  'regions' => array(
    'mini' => t('Top Content'),
    'mini-center' => t('Center Content'),
    'left-menu' => t('Left menu'),
    'mini-center-secondary' => t('Secondary Center Content'),
    'mini-bottom' => t('Bottom Content')
  ),
);
