<?php
/**
 * @file
 * Code for the OS2sub Uses and Tools feature.
 */

include_once 'os2sub_uses_and_tools.features.inc';
/**
 * Filter callbacks.
 */
function _os2sub_uses_and_tools_filters_kill_nbsp($text, $filter) {
  return preg_replace('/&nbsp;/', ' ', $text);
}

/**
 * Filter tips.
 */
function _os2sub_uses_and_tools_filters_kill_nbsp_tips($filter, $format, $long = FALSE) {
  if (!$long) {
    // This string will be shown in the content add/edit form.
    return t('Don\'t use non-breaking spaces.  Ever.');
  }
  else {
    // And this one on the "Filter Tips" page.
    return t('Non-breaking spaces are evil and will be eradicated.');
  }
}