<?php

/**
 * @file
 * Code for the Subsites Paragraphs module.
 * 
 * This module get hidden Background and Sides switch variables and make it available in templates.
 */

function subsites_paragraphs_preprocess_entity(&$variables) {
  if ($variables['entity_type'] == 'paragraphs_item') {
    //get hidden field field_paragraph_bg
    $field_paragraph_bg = field_get_items('paragraphs_item', $variables['paragraphs_item'], 'field_paragraph_bg');
    if ($field_paragraph_bg) {
      $variables['classes_array'][] = $field_paragraph_bg[0]['value'];
    }
    else{
      $variables['classes_array'][] = 'bg-white';
    }
    
    //get hidden field field_paragraph_position 
    $field_paragraph_position = field_get_items('paragraphs_item', $variables['paragraphs_item'], 'field_paragraph_position');
    if ($field_paragraph_position) {
      $variables['field_paragraph_position']= $field_paragraph_position[0]['value'];
    }
    
    //get hidden field field_paragraph_pos 
    $field_paragraph_pos = field_get_items('paragraphs_item', $variables['paragraphs_item'], 'field_paragraph_pos');
    if ($field_paragraph_pos) {
      $variables['field_paragraph_pos']= $field_paragraph_pos[0]['value'];
    }
  }
}