<?php

/**
 * @file
 * Code for the Subsites Paragraphs module.
 * 
 * This module get hidden Background and Sides switch variables and make it available in templates.
 */

function subsites_paragraphs_preprocess_entity(&$variables) {
  if ($variables['entity_type'] == 'paragraphs_item') {
    // Get hidden field field_paragraph_bg.
    $field_paragraph_bg = field_get_items('paragraphs_item', $variables['paragraphs_item'], 'field_paragraph_bg');
    if ($field_paragraph_bg) {
      $variables['classes_array'][] = $field_paragraph_bg[0]['value'];
    }
    else {
      $variables['classes_array'][] = 'bg-white';
    }

    // Get hidden field field_paragraph_position.
    $field_paragraph_position = field_get_items('paragraphs_item', $variables['paragraphs_item'], 'field_paragraph_position');
    if ($field_paragraph_position) {
      $variables['field_paragraph_position'] = $field_paragraph_position[0]['value'];
    }
    
    // Get hidden field field_paragraph_pos.
    $field_paragraph_pos = field_get_items('paragraphs_item', $variables['paragraphs_item'], 'field_paragraph_pos');
    $variables['field_paragraph_pos'] = FALSE;
    if ($field_paragraph_pos) {
      $variables['field_paragraph_pos'] = $field_paragraph_pos[0]['value'];
    }

    // Get define class per row for paragraphs.
    $field_paragraph_personale_numrow = field_get_items('paragraphs_item', $variables['paragraphs_item'], 'field_paragraph_personale_numrow');
    if (!empty($field_paragraph_personale_numrow)) {
      $field_paragraph_personale_numrow = reset($field_paragraph_personale_numrow);
      // Pass to tpl amount of colunm in row.
      $variables['col_amount'] = !empty($field_paragraph_personale_numrow['value']) ? $field_paragraph_personale_numrow['value'] : 1;
      // Define a map of column classes depend of row amount.
      $variables['col_class'] = array(
        1 => 'col-xs-12 col-sm-12 col-md-12',
        2 => 'col-xs-12 col-sm-12 col-md-6',
        3 => 'col-xs-12 col-sm-12 col-md-4',
        4 => 'col-xs-12 col-sm-12 col-md-3',
        5 => 'col-xs-12 col-sm-12 col-md-2',
        6 => 'col-xs-12 col-sm-12 col-md-2',
      );
    }
    $entity = $variables['paragraphs_item'];

    // Add new template suggestions for paragraph item inside  paragraph.
    if ($entity->hostEntityType() == 'paragraphs_item') {
      $variables['theme_hook_suggestions'][] = 'paragraphs_item__' . $entity->hostEntityBundle() . '__' . $entity->bundle;
      $variables['theme_hook_suggestions'][] = 'paragraphs_item__' . $entity->hostEntityBundle() . '__' . $entity->bundle . '__' . $variables['view_mode'];
    }
  }
}
