<?php

/**
 * @file
 * Code for the FIC search feature.
 */

include_once 'fic_search.features.inc';

/**
 * Implements hook_form_alter()
 *
 * @param $form
 * @param $form_state
 * @param $form_id
 */
function fic_search_form_alter(&$form, &$form_state, $form_id) {
  global $language;

  if ($form_id == 'views_exposed_form' && $form['#id'] == 'views-exposed-form-os2sub-kulturnaut-search-pane-activities-search') {
    $form['#action'] = url('soeg', array('language', $language));
    $form['search_api_views_fulltext']['#attributes']['placeholder'] = t('Search');
  }

  if ($form_id == 'views_exposed_form' && $form['#id'] == 'views-exposed-form-os2sub-kulturnaut-multi-search-pane-activities-multi-search') {
    $form['#action'] = url('soeg', array('language', $language));
    $form['search_api_views_fulltext']['#attributes']['placeholder'] = t('Search');
  }
}

function fic_search_preprocess_views_view(&$variables) {

  $input = $variables['view']->exposed_raw_input;
  $title = t("Search results for \"@text\"", array('@text'=> array_shift($input)));

  $view = $variables['view'];
  if ($view->name == 'os2sub_kulturnaut_multi_search' && $view->current_display == 'pane_activities_multi_search') {
    $view->set_title($title);
    drupal_set_title($title);
  }
}

